FROM ubuntu:16.04
RUN apt-get update && apt-get install -y cmake build-essential gfortran libboost-all-dev python3-dev zlib1g-dev git
ADD . /app

RUN cd /app && \
    git clean -dfx . && \
    /app/script/build_and_test.sh
